name: MobArenaSigns
version: 1.2.1
author: bittiez
main: US.bittiez.MobArenaSigns.main
api-version: 1.15
permissions:
    MAS.use:
        description: Allow use of a MAS sign.
        default: true
    MAS.create:
        description: Allows creating MAS signs.
        default: op
    MAS.break:
        description: Allows breaking of MAS signs.
        default: op